#!/usr/bin/env bash
# This script displays the content of the file /etc/passwd
# only: username, user id and home directory path for the user using a while loop
while IFS=: read -r line
do
	echo "$line" | cut -f 1,3,6 -d ':'
done < "/etc/passwd"
