#!/usr/bin/env bash
# This script displays the content of the file /etc/passwd
# only: username, user id and home directory path for the user using a while loop
while IFS=: read -r f1 f2 f3 f4 f5 f6 f7
do
	echo "$f1:$f3:$f6"
done < "/etc/passwd"
