#!/usr/bin/env bash
# This script is displaying "Best School" 10 times, but on the 4th displays bad luck, and on the 8th displays good luck
x=1
while [ $x -le 10 ]
do
	if [ $x -eq 4 ]
	then
		echo "bad luck"
	elif [ $x -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((x++))
done
