#!/usr/bin/env bash
#Creating a script that displays the content of the current directory, in a list format and only the part of the name after the first dash is displayed
for i in * 
do
	echo "$i" | cut -f 2- -d '-'
done
